#!/bin/bash

convert -size 1024x1024 icon.svg ./Icon1024.png
convert ./Icon1024.png -resize 256x256 -define icon:auto-resize="256,128,96,64,48,32,16" icon.ico

#convert ./icon.svg -resize 22x22 icon.png
#convert ./icon.svg -resize 44x44 icon@2x.png
#convert ./icon.svg -resize 66x66 icon@3x.png

#convert ./icon-paused.svg -resize 22x22 icon-paused.png
#convert ./icon-paused.svg -resize 44x44 icon-paused@2x.png
#convert ./icon-paused.svg -resize 66x66 icon-paused@3x.png


mkdir MyIcon.iconset
sips -z 16 16     Icon1024.png --out MyIcon.iconset/icon_16x16.png
sips -z 32 32     Icon1024.png --out MyIcon.iconset/icon_16x16@2x.png
sips -z 32 32     Icon1024.png --out MyIcon.iconset/icon_32x32.png
sips -z 64 64     Icon1024.png --out MyIcon.iconset/icon_32x32@2x.png
sips -z 128 128   Icon1024.png --out MyIcon.iconset/icon_128x128.png
sips -z 256 256   Icon1024.png --out MyIcon.iconset/icon_128x128@2x.png
sips -z 256 256   Icon1024.png --out MyIcon.iconset/icon_256x256.png
sips -z 512 512   Icon1024.png --out MyIcon.iconset/icon_256x256@2x.png
sips -z 512 512   Icon1024.png --out MyIcon.iconset/icon_512x512.png
cp Icon1024.png MyIcon.iconset/icon_512x512@2x.png
iconutil -c icns MyIcon.iconset
mv MyIcon.icns icon.icns
rm -R MyIcon.iconset

